server:
  port: 10011
spring:
  application:
    name: jushi-article
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
  jpa:
    open-in-view: true
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
security:
  oauth2:
    resource:
      id: jushi-article
      user-info-uri: http://localhost:8001/uaa/user
      prefer-token-info: false
