server:
  port: 10010
spring:
  application:
    name: jushi-web
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: localhost
  data:
    mongodb:
      uri: mongodb://localhost:27017/jushi
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
security:
  oauth2:
    resource:
      id: jushi-web
      user-info-uri: http://localhost:8001/api/uaa/user
      prefer-token-info: false

logging:
  level:
    #root: debug
    org.springframework.data.mongodb.core: DEBUG
#debug
#logging:
#  level:
#    root: debug

