server:
  port: 6001
spring:
  application:
    name: jushi-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:6524
      eager: true
  jpa:
    open-in-view: true
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    platform: postgres
    url: jdbc:postgresql://45.76.203.138:5432/jushi
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    druid:
      minIdle: 5
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        allow: 127.0.0.1
        url-pattern: /druid/*
        login-password: druid123123
        login-username: druid
      initialSize: 5
      WebStatFilter:
        exclusions:
      maxActive: 30
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
management:
  endpoints:
    web:
      exposure:
        include: '*'
##很重要
security:
  oauth2:
    resource:
      filter-order: 3

#debug
#logging:
#  level:
#    root: debug