server:
  port: 6001
spring:
  application:
    name: jushi-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:6524
      eager: true
  redis:
    host: localhost
  data:
    mongodb:
      uri: mongodb://localhost:27017/jushi
management:
  endpoints:
    web:
      exposure:
        include: '*'
##很重要
security:
  oauth2:
    resource:
      filter-order: 3


logging:
  level:
    #root: debug
    org.springframework.data.mongodb.core: DEBUG